package com.ajayasija.rexsolutions.ui.screens.inspection_lead

val titleList = listOf(
    "Registration Book",
    "Odometer",
    "Chassis Number",
    "Engine Number",
    "Front WS Glass",
    "Full Front",
    "Front Under Carriage",
    "Bonnet Open For Engine",
    "Roof From Outside",
    "Front V Left",
    "Full Left",
    "Back V Left",
    "Back Full",
    "Back Under Carriage",
    "Back Dickey Open",
    "Back V Right",
    "Full Right",
    "Front V Right",
    "Selfie With Car",
    "Tyre 1",
    "Tyre 2",
    "Tyre 3",
    "Tyre 4",
    "Dashboard Inside",
    "Front Seat",
    "Back Seat",
    "Roof From Inside",
    "Extra 1",
    "Extra 2",
    "Extra 3",
)


enum class GetMedia {
    CHASSIS,
    ODOMETER,
    REGISTRATIONBOOK,
    ENGINENUMBER,
    FRONTWSGLASS,
    FULLFRONT,
    FRONTUNDERCARRIAGE,
    BONNETOPENFORENGINE,
    ROOFFROMOUTSIDE,
    FRONTVLEFT,
    FULLLEFT,
    BACKVLEFT,
    BACKFULL,
    BACKUNDERCARRIAGE,
    BACKDICKEYOPEN,
    BACKVRIGHT,
    FULLRIGHT,
    FRONTVRIGHT,
    SELIEWITHCAR,
    TYRE1,
    TYRE2,
    TYRE3,
    TYRE4,
    DASHBOARDINSIDE,
    FRONTSEAT,
    BACKSEAT,
    ROOFFROMINSIDE,
    EXTRA1,
    EXTRA2,
    EXTRA3,
    VIDEO
}